// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/yigitsadic/wotblitz_example/ent/module"
	"github.com/yigitsadic/wotblitz_example/ent/schema"
	"github.com/yigitsadic/wotblitz_example/ent/tank"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	moduleFields := schema.Module{}.Fields()
	_ = moduleFields
	// moduleDescName is the schema descriptor for name field.
	moduleDescName := moduleFields[0].Descriptor()
	// module.NameValidator is a validator for the "name" field. It is called by the builders before save.
	module.NameValidator = moduleDescName.Validators[0].(func(string) error)
	// moduleDescModuleType is the schema descriptor for moduleType field.
	moduleDescModuleType := moduleFields[1].Descriptor()
	// module.ModuleTypeValidator is a validator for the "moduleType" field. It is called by the builders before save.
	module.ModuleTypeValidator = moduleDescModuleType.Validators[0].(func(string) error)
	// moduleDescCreatedAt is the schema descriptor for createdAt field.
	moduleDescCreatedAt := moduleFields[2].Descriptor()
	// module.DefaultCreatedAt holds the default value on creation for the createdAt field.
	module.DefaultCreatedAt = moduleDescCreatedAt.Default.(func() time.Time)
	tankFields := schema.Tank{}.Fields()
	_ = tankFields
	// tankDescName is the schema descriptor for name field.
	tankDescName := tankFields[0].Descriptor()
	// tank.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tank.NameValidator = tankDescName.Validators[0].(func(string) error)
	// tankDescIsPremium is the schema descriptor for isPremium field.
	tankDescIsPremium := tankFields[2].Descriptor()
	// tank.DefaultIsPremium holds the default value on creation for the isPremium field.
	tank.DefaultIsPremium = tankDescIsPremium.Default.(bool)
	// tankDescTankClass is the schema descriptor for tankClass field.
	tankDescTankClass := tankFields[3].Descriptor()
	// tank.TankClassValidator is a validator for the "tankClass" field. It is called by the builders before save.
	tank.TankClassValidator = tankDescTankClass.Validators[0].(func(string) error)
	// tankDescCountry is the schema descriptor for country field.
	tankDescCountry := tankFields[4].Descriptor()
	// tank.CountryValidator is a validator for the "country" field. It is called by the builders before save.
	tank.CountryValidator = tankDescCountry.Validators[0].(func(string) error)
	// tankDescCreatedAt is the schema descriptor for createdAt field.
	tankDescCreatedAt := tankFields[5].Descriptor()
	// tank.DefaultCreatedAt holds the default value on creation for the createdAt field.
	tank.DefaultCreatedAt = tankDescCreatedAt.Default.(func() time.Time)
}
