// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Module is the predicate function for module builders.
type Module func(*sql.Selector)

// Tank is the predicate function for tank builders.
type Tank func(*sql.Selector)
